# This workflow will install Python dependencies, run tests and deploy the app
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: CI/CD Push

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test_and_deploy:
    name: Run Tests and Deploy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      run: |
        python3 -m pytest
    - name: Test with behave
      run: |
        python3 -m behave
    - name: Deploy code
      run: |
        curl -X POST -H "x-api-key: ${{ secrets.API_KEY }}" -H "Content-Type: application/json" -d '{}' https://16kp6jr2cj.execute-api.us-east-1.amazonaws.com/Production
    - name: Verify the app is up and running
      run: |
        curl http://44.218.113.51
